"""add feedback table

Revision ID: 599297391779
Revises: 3fe17d55ce34
Create Date: 2026-02-05 10:28:07.548503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599297391779'
down_revision = '3fe17d55ce34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
