"""add products table

Revision ID: 685774d77869
Revises: 6c024b8d056d
Create Date: 2026-02-05 12:02:54.878832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685774d77869'
down_revision = '6c024b8d056d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
